# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Bun.js CI

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    name: Use bun ${{ matrix.bun-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bun-version: [1.1.26, latest, 1.1.25]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        cache-hit: false
    - run: curl -fsSL https://bun.sh/install | bash
    - run: bun --version
    
    - run: sudo bun install
    - run: sudo bun run build
  

