# This workflow will do a clean installation of bun and its dependencies, check the version then build the source code and run

name: Setup Bun Runtime

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:
    name: Install and use the latest bun version
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
       cache: true
       cache-bin: true
       bun-version: latest
       token: 'gh-token'
       
    - name: Check bun version
      run: bun --version
      
    - name: Check bun version
      run: bun --version
    
    - name: Install dependencies
      run: bun install

    - name: Run tests
      run: bun test
    
    - name: Build and run the source code
      run: bun run build
  

