name: Deploy Landing Page

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    permissions:
        contents: write
        pages: write
    
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies
      run: |
        cd landing-page
        bun install

    - name: Build and Export Landing Page
      run: |
        cd landing-page
        bun run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./landing-page/deployment
        
        
        # cname: your-website-name.com # Optional: Custom domain if needed
