name: Wiki Content Sync

on:
  push:
    branches:
      - production
      - development
    paths:
      - "docs/**"
  repository_dispatch:
    types: [docs]
  workflow_dispatch:

jobs:
  sync-content-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Sync docs folder to wiki
        uses: cmbrose/github-docs-to-wiki@v0.20
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          convertRootReadmeToHomePage: true
          defaultBranch: production