name: Superlinter

on:
  push:
    branches:
      - production
      - development
      - feature/*
      - hotfix/*
      - release/*
  pull_request:
    branches:
      - production
      - development
      - feature/*
      - hotfix/*
      - release/*

jobs:
    super-lint:
        name: Lint Code Base
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2
            - name: Super-Linter
              uses: github/super-linter@v4
              env:
                  DEFAULT_BRANCH: production
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VALIDATE_JAVASCRIPT_ES: true
                  VALIDATE_TYPESCRIPT: true